app:
  name: condomanagement
  version: 1.0.0
  description: Condo Management System
  Host: localhost
  Port: 5001
  Timeout: 60
  timeout_format: second


logging:
  level: debug
  format: json

api:
  rate_limit: 100
  timeout: 30
  timeout_format: second
